### PR TITLE
Regofdapppub

### PR DESCRIPTION
**Pull request by sup1212errrrlol**
eossuperboot

### CODE REVIEW

**Comment by duc811997** [comment]
Duplicate of #

**Comment by duc811997** [comment]
EOS6yeci8HTK8EuG34kRnCq7Q5VLpXfUg7HXYnuCPzjqZXGuU3BPx

**Review by duc811997 — COMMENTED** [review]
cnfikqnvx5cw

**Comment by BESTczm** [comment]
eossuperboot

**Pull request closed without merging**
